### ISSUE TITLE
Clarify some `moveToTrack` params

### ISSUE THREAD

**Issue by Klustre** [aenhancers/types-for-adobe-extras#1]
Found out 2 of the 4 params for [`QETrackItem.moveToTrack`](https://github.com/aenhancers/types-for-adobe-extras/blob/master/Premiere/12.0/qeDom.d.ts#L305)
```js
QETrackItem.moveToTrack(
  trackIndex: number,
  p1: number,
  p2: string,
  copy?: boolean // optional: default `false`
): boolean
```

**Comment by justintaylor-dev** [comment]
Thanks @Klustre! Added in 3d3b9b1b0852080ca8eb09cd0d2d19cc6318aa26
